### PR TITLE
Handle attachments from the "same" test from different branches/nodes

### LINKED ISSUE #202: Attachments not correct when a test is run multiple times in different branches)
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.504.3
OS: Windows 11 - 10.0
Java: 21.0.1 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
antisamy-markup-formatter:173.v680e3a_b_69ff3
apache-httpcomponents-client-4-api:4.5.14-269.vfa_2321039a_83
asm-api:9.9.1-189.vb_5ef2964da_91
bootstrap5-api:5.3.8-890.v1c5cf4fa_178e
bouncycastle-api:2.30.1.82-277.v70ca_0b_877184
caffeine-api:3.2.3-194.v31a_b_f7a_b_5a_81
checks-api:373.vfe7645102093
commons-lang3-api:3.20.0-109.ve43756e2d2b_4
commons-text-api:1.15.0-210.v7480a_da_70b_9e
display-url-api:2.217.va_6b_de84cc74b_
durable-task:639.vefb_3d8372f6d
echarts-api:6.0.0-1146.v5c8f3b_8f0573
font-awesome-api:7.0.1-859.v128d3a_efb_6e5
instance-identity:203.v15e81a_1b_7a_38
ionicons-api:94.vcc3065403257
jackson2-api:2.20.1-423.v13951f6b_6532
jakarta-activation-api:2.1.4-1
jakarta-mail-api:2.1.5-1
jakarta-xml-bind-api:4.0.6-10.v9b_7e1d1fc40b_
javax-activation-api:1.2.0-8
jaxb:2.3.9-133.vb_ec76a_73f706
jquery3-api:3.7.1-594.vb_3864f326cf0
json-api:20250517-173.v596efb_962a_31
junit:1369.v15da_00283f06
junit-attachments:999999-SNAPSHOT (private-7b846a81-jnord)
mailer:525.v2458b_d8a_1a_71
plugin-util-api:6.1167.v022176c7e0ca_
prism-api:1.30.0-609.vf0a_df102d9a_f
scm-api:724.v7d839074eb_5c
script-security:1385.v7d2d9ec4d909
snakeyaml-api:2.5-143.v93b_c004f89de
structs:362.va_b_695ef4fdf9
workflow-api:1384.vdc05a_48f535f
workflow-basic-steps:1098.v808b_fd7f8cf4
workflow-cps:4238.va_6fb_65c1f699
workflow-durable-task-step:1464.v2d3f5c68f84c
workflow-job:1559.va_a_533730b_ea_d
workflow-scm-step:466.va_d69e602552b_
workflow-step-api:710.v3e456cc85233
workflow-support:1010.vb_b_39488a_9841
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows, Unix, controller or agents does not matter.

### Reproduction steps

1. create a pipeline with the following script
```groovy
def simulateTest(String folder) {
    dir(folder) {
        writeFile file: 'attachment.txt', text: "this is $folder"
        writeFile file: 'test.xml', text: '''<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" version="3.0.2" name="com.example.MyTest" time="1" tests="1" errors="0" skipped="0" failures="0">
  <testcase name="someTestWithAttachments" classname="com.example.MyTest" time="1">
    <system-out><![CDATA[This is some system.out data from branch %%BRANCH%%
]]></system-out>
    <system-err><![CDATA[This is some system.err.data with an attachment
    [[ATTACHMENT|attachment.txt]]
]]></system-err>
  </testcase>
</testsuite>
        '''.replace("%%BRANCH%%", folder)
        junit stdioRetention: 'ALL', testDataPublishers: [attachments()], testResults: 'test.xml' 
    }
}

node {
    parallel firstBranch: {
        simulateTest("a")
    }, secondBranch: {
        simulateTest("b")
    },
    failFast: false
}
```
2. run the pipeline

### Expected Results

the attachments for the tests contain 2 attachments.

One should have the content `this is a`
One should have the content `this is b`

WHen viewing a single test run only one attachment (which is the branch specific run) is shown

### Actual Results

2 attachments are listed - but following the links both have the same content (`this is b` in my case)

when viewing an speciv test run on a specific branch (`http://localhost:8080/jenkins/job/testing/1/testReport/com.example/MyTest/secondBranch___someTestWithAttachments/`) you see 2 attachments.

### Anything else?

Possible a dupe of #25 #26 #165 however as this as explicit steps to reproduce and exactly describes the issue I am facing in the acceptance-test-harness and in other places I am going to focus on this issue only

### Are you interested in contributing a fix?

yes

### PR DESCRIPTION
**Pull request by jtnord**
When the same test was recorded with the same attachment paths (but on different nodes) then wen viewing test results you would only be able to see one of the attachments.

The testData now records the flow ids so that attachments from different flows can be disambiguated.

Also tested interactively by:
* without the fix, create a pipeline using the pipeline from the unit tests
* ran a build and checked the test results and data (only one branch is present)
* upgraded the plugin to a locally built version with this fix
* checked the old results where still present (only one attachment was still obtainable)
* ran a build and checked the test results and data (both attachments are available)

fixes: #202

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests that demonstrate the feature works or the issue is fixed

### CODE REVIEW

File: src/main/java/hudson/plugins/junitattachments/GetTestDataMethodObject.java [hunk 1]
```diff
@@ -86,8 +89,27 @@ public GetTestDataMethodObject(Run<?, ?> build, @NonNull FilePath workspace,
         this.build = build;
         this.testResult = testResult;
         this.listener = listener;
-        attachmentsStorage = AttachmentPublisher.getAttachmentPath(build);
         this.workspace = workspace;
+
+        List<String> blocks = Collections.emptyList();
+        for (SuiteResult suite : testResult.getSuites()) {
```
Comment (jtnord) [inline src/main/java/hudson/plugins/junitattachments/GetTestDataMethodObject.java:95]: the tests results we are passed should all ceom from a single `junit` step and as such the enclosing blocks should be the same across all suites.

File: src/main/java/hudson/plugins/junitattachments/GetTestDataMethodObject.java [hunk 2]
```diff
@@ -86,8 +89,27 @@ public GetTestDataMethodObject(Run<?, ?> build, @NonNull FilePath workspace,
...
+            List<String> eb = suite.getEnclosingBlocks();
```
Comment (jtnord) [inline src/main/java/hudson/plugins/junitattachments/GetTestDataMethodObject.java:96]: use block IDs and not block names, as the names are supplied by humans so we would need to escape.
IDs are numbers so we do not have to sanitize them for the filesystem or UI or elsewhere.

File: src/main/java/hudson/plugins/junitattachments/TestClassAttachmentTestAction.java [hunk 3]
```diff
@@ -11,27 +11,39 @@ public class TestClassAttachmentTestAction extends AttachmentTestAction {
...
+        this.blocks = blocks;
     }
 
     public Map<String, List<String>> getAttachments() {
         return attachments;
     }
 
+    // disambiguate actions where we have blocks for classes
+    @Override
+    public String getUrlName() {
```
Comment (jtnord) [inline src/main/java/hudson/plugins/junitattachments/TestClassAttachmentTestAction.java:35]: each of our `TestData` that has an entry for a class produces a TestClassAttachmentTestAction - so this causes all of them to have a unique name (regarless of if there is one or more)

File: src/main/java/hudson/plugins/junitattachments/AttachmentPublisher.java [hunk 4]
```diff
@@ -143,20 +170,24 @@ public List<TestAction> getTestAction(hudson.tasks.junit.TestObject t) {
             }
 
             FilePath root = getAttachmentPath(testObject.getRun());
+            if (enclosingBlocks != null && !enclosingBlocks.isEmpty()) {
+                root = root.child(String.join("-", enclosingBlocks));
+            }
             // Historical builds might have attachments stored in class level directories
-            boolean attachmentsStoredAtClassLevel = areAttachmentsStoredAtClassLevel(root, fullName, tests);
+            boolean attachmentsStoredAtClassLevel = enclosingBlocks == null && areAttachmentsStoredAtClassLevel(root, fullName, tests);
```
Comment (jtnord) [inline src/main/java/hudson/plugins/junitattachments/AttachmentPublisher.java:178]: if `enclosingBlocks` is not `null` then by definition we can not be an historical build.

File: src/test/java/hudson/plugins/junitattachments/AttachmentPublisherPipelineTest.java [hunk 5]
```diff
@@ -132,6 +141,118 @@ void testBothWellKnownFilenamesAndPatternAreAttached(JenkinsRule jenkinsRule) th
...
+        for (CaseResult cr : passedTests) {
+            // which branch was this in
+            List<String> branchNames = cr.getEnclosingFlowNodeNames();
+            if (branchNames.contains("firstBranch")) {
+                assertThat(getTestAttachementAsText(jenkinsRule, cr), is("this is branch firstBranch"));
+            }
+            if (branchNames.contains("secondBranch")) {
+                assertThat(getTestAttachementAsText(jenkinsRule, cr), is("this is branch secondBranch"));
+            }
+        }
```
[the remark this answers is not in the document]
Comment (jtnord) [reply src/test/java/hudson/plugins/junitattachments/AttachmentPublisherPipelineTest.java:165]: copilot you should never use `assertTrue` without a message :-(

File: src/test/java/hudson/plugins/junitattachments/AttachmentPublisherPipelineTest.java [hunk 6]
```diff
@@ -132,6 +141,118 @@ void testBothWellKnownFilenamesAndPatternAreAttached(JenkinsRule jenkinsRule) th
...
+            url = new URL(url, action.getUrl("someTestWithAttachments", "attachment.txt"));
+            String s = fromURL(url);
+            if ("this is branch firstBranch".equals(s)) {
+                foundFirstBranch = true;
+            } else if("this is branch secondBranch".equals(s)) {
+                foundSecondBranch = true;
+            }
+        }
+        assertTrue(foundFirstBranch, "Found first branch");
+        assertTrue(foundSecondBranch, "Found second branch");
```
[the remark this answers is not in the document]
Comment (jtnord) [reply src/test/java/hudson/plugins/junitattachments/AttachmentPublisherPipelineTest.java:208]: co-pilot you are talking rubbish

https://github.com/jenkinsci/junit-attachments-plugin/runs/64682528027

`Found second branch ==> expected: <true> but was: <false>` 

This reads to me as I expected "found second branch" to be true but was false.  Your suggestion would be

`Did not find expected attachment for secondBranch ==> expected: <true> but was: <false>` 

which is the obvious of your statement "but these messages read like success messages"

File: src/test/java/hudson/plugins/junitattachments/AttachmentPublisherPipelineTest.java [hunk 7]
```diff
@@ -132,6 +141,118 @@ void testBothWellKnownFilenamesAndPatternAreAttached(JenkinsRule jenkinsRule) th
...
+     * Obtain the string content of a single attachment from a single test.
+     * @param cr the Single test to obtain the attachment for.
+     * @return String content of the attachment for the test
+     * @throws IOException if we could not obtain the test data (using HTTP to download)
+     */
+    private static String getTestAttachementAsText(JenkinsRule jenkinsRule, CaseResult cr) throws IOException {
+        List<TestCaseAttachmentTestAction> testCaseAttachmentTestActions = cr.getTestActions().stream()
+                .filter(TestCaseAttachmentTestAction.class::isInstance)
+                .map(TestCaseAttachmentTestAction.class::cast)
+                .collect(Collectors.toList());
```
[the remark this answers is not in the document]
Comment (jtnord) [reply src/test/java/hudson/plugins/junitattachments/AttachmentPublisherPipelineTest.java]: 944370fa3bc80345dad0d27dc07b2d7c2c85acf8

**Comment by jonesbusy** [comment]
Thanks!
